services:
  cloudflared:
    image: cloudflare/cloudflared:2026.3.0
    container_name: lab4_professor_cloudflared
    restart: unless-stopped
    command:
      - tunnel
      - --no-autoupdate
      - --protocol
      - http2
      - run
      - --token
      - ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      caddy:
        condition: service_healthy
